export type RedirectCode =
  | 'permanent'
  | 301
  | 'temp'
  | 302
  | 'seeother'
  | 303
  | 'gone'
  | 410
export type ErrorCode =
  | 400
  | 401
  | 402
  | 403
  | 404
  | 405
  | 406
  | 410
  | 412
  | 415
  | 418
  | 420
  | 422
  | 426
  | 429
  | 451
  | 500
  | 501
  | 502
  | 503
  | 504
  | 505

export interface HTAccessFileOptions {
  topLevelFile: boolean
  errorPages?: Array<{code: ErrorCode; filePath: string}>
  redirects?: Array<{status: RedirectCode; source: string; destination: string}>
  cachingRules?: Array<{type: 'default' | string; seconds: number}>
}

const ensureDotHTML = (filePath: string) => {
  return filePath.endsWith('.html') ? filePath : `${filePath}.html`
}

export const htAccessFileContent = ({
  topLevelFile,
  errorPages,
  redirects,
  cachingRules
}: HTAccessFileOptions) => {
  let fileEntries = [
    '# This file is generated by astro-htaccess-manager do not edit it directly',
    ''
  ]

  if (errorPages) {
    fileEntries = fileEntries.concat([
      '# Error Pages',
      ...errorPages.map(({code, filePath}) => {
        if (topLevelFile) {
          return `ErrorDocument ${code} ${ensureDotHTML(filePath)}`
        }

        return `ErrorDocument ${code} ${filePath}/index.html`
      }),
      ''
    ])
  }

  if (redirects) {
    fileEntries = fileEntries.concat([
      '# Redirects',
      ...redirects.map(({status, source, destination}) => {
        return `RedirectMatch ${status} ^${source}(/(index.html)?)?$ ${destination}`
      }),
      ''
    ])
  }

  if (cachingRules) {
    fileEntries = fileEntries.concat([
      '# Caching Rules',
      'ExpiresActive On',
      /*...cachingRules.map(({type, seconds}) => {
        return `Expires${type === 'default' ? 'Default' : `ByType ${type}`} "access plus ${seconds} seconds"`
      }),*/
      ...cachingRules.map(({type, seconds}) => {
        if (type === 'default') {
          return `Header set Cache-Control "max-age=${seconds}, public"`
        }

        return [
          `<FilesMatch "\.(${type})$">`,
          `\tHeader set Cache-Control "max-age=${seconds}, public"`,
          `</FilesMatch>`
        ].join('\n')
      })
    ])
  }

  const contents = fileEntries.join('\n')

  return contents
}
